backend:
  name: git-gateway
  branch: main

media_folder: "src/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - name: "index"
        label: "Page d'accueil"
        file: "src/pages/index.md"
        fields:
          - { label: "Titre", name: "title", widget: "string" }
          - { label: "Contenu", name: "body", widget: "markdown" }
